[theme]
# Primary accent color for interactive elements.
primaryColor = "#697565"

# Background color for the main content area.
backgroundColor = "#181C14"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#3C3D37"

# Color used for almost all text.
textColor = "#ECDFCC"

[client]
toolbarMode = "viewer"